[package]
name = "discogs"
version = "0.1.0"
authors = ["Simon Persson <simon@flaskpost.org>"]

[dependencies]
rustc-serialize = "*"

[dependencies.ease]
git = "https://github.com/SimonPersson/ease.git"
